"""
build_docs_manifest.py - Generates docs_manifest.json for the Docs Viewer.
Scans repo for .md files, excludes node_modules, .git, _archive, venv, dist.
Output goes to repo root for relative-path access from the viewer iframe.
"""
from pathlib import Path
import json
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent.parent.resolve()
EXCLUDE_DIRS = {
    'node_modules', '.git', '_archive', 'venv', 'env', '.venv',
    'dist', '.next', '__pycache__', '.cache', '.vite', 'coverage',
    '.claude', '.pytest_cache'
}

DIR_LABELS = {
    '.': 'Pre Atlas (Root)',
    'services/cognitive-sensor': 'Cognitive Sensor',
    'services/cognitive-sensor/cycleboard': 'CycleBoard',
    'services/cognitive-sensor/cycleboard/docs': 'CycleBoard Docs',
    'services/delta-kernel': 'Delta Kernel',
    'services/delta-kernel/specs': 'Delta Kernel Specs',
    'research/uasc-m2m': 'UASC-M2M Research',
    'research/uasc-m2m/spec': 'UASC Specifications',
    'research/uasc-m2m/UASC-M2M': 'UASC Sub-Project',
    'research/uasc-m2m/generic': 'UASC Generic Framework',
    'apps/webos-333': 'WebOS 333',
    'apps/blueprint-generator': 'Blueprint Generator',
    'contracts': 'Contracts & Schemas',
    'data': 'Data & Content',
    'scripts': 'Scripts',
    'services/delta-kernel/web': 'Delta Kernel Web',
}


def scan_md_files():
    """Walk repo for .md files, skip excluded dirs."""
    files = []
    for md_file in sorted(REPO_ROOT.rglob('*.md')):
        parts = md_file.relative_to(REPO_ROOT).parts
        if any(excluded in parts for excluded in EXCLUDE_DIRS):
            continue

        rel_path = md_file.relative_to(REPO_ROOT).as_posix()
        parent = md_file.parent.relative_to(REPO_ROOT).as_posix()
        if parent == '.':
            parent = '.'

        stat = md_file.stat()
        # Read file content for inline embedding (file:// protocol support)
        try:
            content = md_file.read_text(encoding='utf-8', errors='replace')
        except Exception:
            content = None

        files.append({
            'path': rel_path,
            'name': md_file.name,
            'dir': parent,
            'size': stat.st_size,
            'modified': int(stat.st_mtime),
            'content': content,
        })
    return files


def build_tree(files):
    """Group files by directory for sidebar tree rendering."""
    tree = {}
    for f in files:
        d = f['dir']
        if d not in tree:
            tree[d] = []
        tree[d].append(f)
    return tree


def main():
    files = scan_md_files()
    tree = build_tree(files)

    manifest = {
        'generated_at': datetime.now().isoformat(),
        'total_files': len(files),
        'dir_labels': DIR_LABELS,
        'files': files,
        'tree': tree,
    }

    # Write JSON (lightweight, no embedded content — for API/programmatic use)
    manifest_lite = {**manifest, 'files': [
        {k: v for k, v in f.items() if k != 'content'} for f in files
    ], 'tree': {
        d: [{k: v for k, v in f.items() if k != 'content'} for f in flist]
        for d, flist in tree.items()
    }}
    out_path = REPO_ROOT / 'docs_manifest.json'
    out_path.write_text(json.dumps(manifest_lite, indent=2))

    # Write JS (full with embedded content — works on file:// protocol)
    js_path = REPO_ROOT / 'docs_manifest.js'
    js_path.write_text(
        '// Auto-generated by build_docs_manifest.py — do not edit\n'
        'window.DOCS_MANIFEST = ' + json.dumps(manifest) + ';\n'
    )

    print(f'[OK] docs_manifest.json + .js: {len(files)} files across {len(tree)} directories')


if __name__ == '__main__':
    main()
