"""
Generate docs/CLI_REFERENCE.md from cli_manifest.json.

The JSON is the source of truth. Re-run this script after editing it.
"""

import json
from pathlib import Path

BASE = Path(__file__).parent.resolve()
MANIFEST = BASE / "cli_manifest.json"
OUT = BASE.parent.parent / "docs" / "CLI_REFERENCE.md"

AUTONOMY_ICON = {"human": "Human", "scheduled": "Scheduled", "autonomous": "Autonomous"}


def fmt_list(items: list[str]) -> str:
    if not items:
        return "_none_"
    return "<br>".join(f"`{i}`" for i in items)


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    clis = manifest["clis"]
    version = manifest.get("version", "?")
    generated_at = manifest.get("generated_at", "")

    lines: list[str] = []
    lines.append("# Pre Atlas CLI Reference")
    lines.append("")
    lines.append(f"_Generated from `services/cognitive-sensor/cli_manifest.json` (v{version}, {generated_at})._")
    lines.append("_Do not edit this file by hand. Edit the manifest and re-run `python generate_cli_reference.py`._")
    lines.append("")
    lines.append("## CLIs at a glance")
    lines.append("")
    lines.append("| CLI | Runtime | Autonomy | Commands | Help |")
    lines.append("|---|---|---|---|---|")
    for name, cli in clis.items():
        lines.append(
            f"| **`{name}`** | {cli['runtime']} | {AUTONOMY_ICON.get(cli['autonomy'], cli['autonomy'])} "
            f"| {len(cli['commands'])} | `{cli['help_invocation']}` |"
        )
    lines.append("")
    lines.append("## Autonomy levels")
    lines.append("")
    for lvl, desc in manifest.get("autonomy_levels", {}).items():
        lines.append(f"- **{lvl}** — {desc}")
    lines.append("")

    for name, cli in clis.items():
        lines.append("---")
        lines.append("")
        lines.append(f"## `{name}`")
        lines.append("")
        lines.append(cli.get("description", ""))
        lines.append("")
        lines.append(f"- **Path:** `{cli['path']}`")
        if cli.get("launcher"):
            lines.append(f"- **Launcher:** `{cli['launcher']}`")
        lines.append(f"- **Runtime:** `{cli['runtime']}`")
        lines.append(f"- **Autonomy:** {AUTONOMY_ICON.get(cli['autonomy'], cli['autonomy'])}")
        lines.append(f"- **Help:** `{cli['help_invocation']}`")
        if cli.get("output_format"):
            lines.append(f"- **Output format:** {cli['output_format']}")
        if cli.get("safety"):
            lines.append(f"- **Safety:** {cli['safety']}")
        lines.append("")
        lines.append("**Reads**")
        lines.append("")
        lines.append(fmt_list(cli.get("reads", [])))
        lines.append("")
        lines.append("**Writes**")
        lines.append("")
        lines.append(fmt_list(cli.get("writes", [])))
        lines.append("")
        lines.append("**Commands**")
        lines.append("")
        lines.append("| Command | Args | Description | Example |")
        lines.append("|---|---|---|---|")
        for cmd_name, cmd in cli["commands"].items():
            args = " ".join(cmd.get("args", [])) or "_none_"
            desc = cmd.get("description", "").replace("|", "\\|")
            example = cmd.get("example", "")
            lines.append(f"| `{cmd_name}` | `{args}` | {desc} | `{example}` |")
        lines.append("")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    cli_count = len(clis)
    cmd_count = sum(len(c["commands"]) for c in clis.values())
    print(f"Wrote {OUT.relative_to(BASE.parent.parent)} ({cli_count} CLIs, {cmd_count} commands)")


if __name__ == "__main__":
    main()
